# This config does the following:
#
# - Uses a network 'dind-lab' to connect containers.
#   This must be created with 'docker network create --driver bridge dind-lab'
#
# - Start a couple services:
#   - devbox: A container with basic dev tools installed.
#     Built at compose-up time from 'Dockerfile.devbox'.
#   - pw: A Playwright container listening on port 3000
#   - android-emulator: An android emulator

services:
  devbox:
    image: devbox:latest
    build:
      context: .
      dockerfile: Dockerfile.devbox
    volumes:
      - ./:/workspace
    working_dir: /workspace
    tty: true
    stdin_open: true
    networks:
      - dind-lab
    environment:
      # Playwright Test will connect to the remote browser server
      - PW_TEST_CONNECT_WS_ENDPOINT=ws://pw:3000/

  pw:
    image: mcr.microsoft.com/playwright:v1.49.0-noble
    user: pwuser
    init: true
    ipc: host
    shm_size: "2gb"
    networks:
      - dind-lab
    command: >
      /bin/sh -lc "npx -y playwright@1.49.0 run-server --port 3000 --host 0.0.0.0"

  android-emulator:
    image: budtmo/docker-android:emulator_14.0
    privileged: true
    devices:
      - /dev/kvm
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
    networks:
      - dind-lab
    ports:
      - "6080:6080"
      - "5554:5554"
      - "5555:5555"
    volumes:
      - android-data:/home/androidusr
    shm_size: "2gb"

#  app:
#    image: node:22
#    working_dir: /workspace
#    volumes:
#      - ./:/workspace
#    networks:
#      - dind-lab
#    command: >
#      /bin/sh -lc "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
#    ports:
#      - "5173:5173"

networks:
  dind-lab:
    external: true
    name: dind-lab

volumes:
  android-data:
